services:
    app:
        build: .
        # if you have a corresponding image hosted on Docker Hub, you can use an image definition instead of a build definition
        # image: YOUR-DOCKER-ID/IMAGE-NAME
        ports: 
            - 5173:80
